version: "3.8"

services:

  # MQTT Broker
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/mosquitto/config
    restart: always

  # Apache Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=${ZOOKEEPER_CLIENT_PORT}
      - ZOOKEEPER_TICK_TIME=${ZOOKEEPER_TICK_TIME}
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=${KAFKA_BROKER_ID}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS}
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    depends_on:
      - zookeeper
    restart: always

  # PostgreSQL DB
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  # Sensor Simulators
  sensor-berat:
    build: ./sensor-berat
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
    depends_on:
      - mqtt-broker
    restart: always

  sensor-kecepatan:
    build: ./sensor-kecepatan
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
    depends_on:
      - mqtt-broker
    restart: always

  sensor-status:
    build: ./sensor-status
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
    depends_on:
      - mqtt-broker
    restart: always

  # MQTT to Kafka Bridge
  mqtt-bridge:
    build: ./mqtt-bridge
    depends_on:
      - mqtt-broker
      - kafka
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
    restart: always

  # Processor Service
  processor-service:
    build: ./processor-service
    depends_on:
      - kafka
      - postgres
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - POSTGRES_HOST=${POSTGRES_HOST}
    restart: always

  # OEE API Service
  oee-service:
    build: ./oee-service
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
    restart: always

  # Dashboard (React)
  frontend-dashboard:
    build:
      context: ./frontend-dashboard
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - oee-service
    restart: always

  # # Dashboard (Streamlit)
  # dashboard:
  #   build: ./dashboard
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - oee-service
  #   restart: always

volumes:
  pgdata:
